config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  get "/map", to: "map#index", as: :map
  patch "/map/station_image", to: "map#upload_station_image", as: "station_image"
  get "/map/station_image", to: "map#fetch_image"

  post "/api/overpass/stations", to: "overpass#stations"

  get "/proxy/map-tiles/thunderforest", to: "proxy#maptiles_thunderforest"
  get "/proxy/map-tiles/jawg", to: "proxy#maptiles_jawg"

  scope module: 'api' do
    get '/api/countries/:country_code', to: "country_data#fetch", as: "country_data"
  end

  get '/info', to: 'info#index', as: 'info'

  #Account system
  scope module: "account" do
    get '/users/sign_up', to: 'users#new', as: 'signup'
    post "/users/sign_up", to: 'users#create'

    get '/users/login', to: 'sessions#new', as: 'login'
    delete 'users/logout', to: 'sessions#destroy', as: 'logout'
    post '/users/login', to: 'sessions#create'

    get '/users/profile', to: 'users#profile', as: 'profile'
    delete '/users/profile', to: 'users#destroy', as: 'destroy_user'
    get '/users/settings', to: 'users#settings', as: 'settings'
    patch '/users/settings/avatar', to: 'users#upload_avatar', as: 'upload_avatar'
    get '/users/:user_id', to: 'users#view_profile', as: 'view_profile'

    get '/auth/password', to: 'auth#edit_password', as: 'edit_password'
    patch '/auth/password', to: 'auth#update_password'

    get '/auth/reset', to: 'password_resets#new'
    post '/auth/reset', to: 'password_resets#create'

    get '/auth/reset/edit', to: 'password_resets#edit'
    patch '/auth/reset/edit', to: 'password_resets#update'

    patch '/users/change_name', to: 'users#change_username'

    get '/friends', to: 'friends#index'
    post '/friends', to: 'friends#send_invitation'
    patch '/friends/accept_invitation', to: 'friends#accept_invitation', as: 'accept_invitation'
    delete '/friends/delete_invitation', to: 'friends#delete_invitation', as: 'delete_invitation'
    delete '/friends/unfriend', to: 'friends#unfriend', as: 'unfriend'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    if Current.user
      relevant_users =  Current.user.friends.or(User.where(id: Current.user.id))
      @stations = TrainStation.where(user: relevant_users).order(created_at: :desc).limit(10).includes(:user)
    else
      render 'main/welcome'
    end
  end
end

app/views/main/index.html.erb
<div class = "main_header">
    <p>
        <h1 class="sign_header">Activity</h1>
    </p>
</div>

<div class="feed">
  <% if @stations.length > 0%>
    <%@stations.each do |station| %>
      <div class="feed_entry">
        <div class="message-container <%= station.user.id == Current.user.id ? 'user-message' : 'friend-message'%>">
          <div class="feed_message">
            <h3 class="feed_message_head"><b><%= station.user.username %></b> took a photo of a train station</h3>
            <img src="<%= url_for(station.image.variant(resize_to_fit: [300, 300])) %>" alt="Image of <%= station.name %>" class="feed_image" onclick="openModal('<%= url_for(station.image) %>')">
            <p class="feed_info">
              <i class="fa-solid fa-train fa-fw"></i> <%= station.name %> <br><i class="fa-solid fa-calendar-days fa-fw"></i> <%= station.created_at.strftime('%d %B %H:%M')%></p>
          </div>
          <img src="<%=url_for(station.user.avatar.variant(resize_to_fill: [400,400])) %>" alt="User Profile" class="profile-picture_feed" onclick="window.location = '<%= "/users/#{station.user.id}" %>'">
        </div>
      </div>
    <%end %>
  <%else%>
    <div class="no_entries">
      <p>You dont have any photos, yet...</p>
      <i class="fa-solid fa-image"></i>
    </div>
  <% end %>
</div>

<div id="photoViewWrapper" class="modal">
  <span class="close" onclick="closeModal()">&times;</span>
  <img class="modal-content" id="modalImage">
</div>

<script>
    function openModal(url) {
        let modal = document.getElementById("photoViewWrapper");
        let modalImage = document.getElementById("modalImage");
        modal.style.display = "flex";
        modalImage.src = url;
    }

    function closeModal() {
        let modal = document.getElementById("photoViewWrapper");
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        let modal = document.getElementById("photoViewWrapper");
        if (event.target == modal) {
            closeModal();
        }
    }
</script>

app/views/main/welcome.html.erb
<div class = "main_background">
  <div class= "main_content">
    <div class="welcome_login_wrapper">
      <div class = "main_logo">
        <%= link_to "https://github.com/Langschwanzpinguine/Bahnhofottos", target: "_blank" do %>
          <%= image_tag "Bahnhofottos_logo.png", alt: "Bahnhofottos Logo", id: "main_logo" %>
        <% end %>
      </div>
      <h2>Log In</h2>
      <div class = "login">
      <%= form_tag login_path, data: { turbo: false } do %>
        <div class="field">
          <%= label_tag :email %><br />
          <%= text_field_tag :email, params[:email] %>
        </div>
        <div class="field">
          <%= label_tag :password %><br />
          <%= password_field_tag :password %>
        </div>
        <div class="actions"><%= submit_tag "Log In" %></div>
        <%= link_to "Forgot password", auth_reset_path %> <br>
      <% end %>
      </div>
      <h2>Or Sign Up</h2>
      <%= button_to "Create account", signup_path, :method => :get, class: "button main_button" %>
    </div>
  </div>
</div>