config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  get "/map", to: "map#index", as: :map
  patch "/map/station_image", to: "map#upload_station_image", as: "station_image"
  get "/map/station_image", to: "map#fetch_image"

  post "/api/overpass/stations", to: "overpass#stations"

  get "/proxy/map-tiles/thunderforest", to: "proxy#maptiles_thunderforest"
  get "/proxy/map-tiles/jawg", to: "proxy#maptiles_jawg"

  scope module: 'api' do
    get '/api/countries/:country_code', to: "country_data#fetch", as: "country_data"
  end

  get '/info', to: 'info#index', as: 'info'

  #Account system
  scope module: "account" do
    get '/users/sign_up', to: 'users#new', as: 'signup'
    post "/users/sign_up", to: 'users#create'

    get '/users/login', to: 'sessions#new', as: 'login'
    delete 'users/logout', to: 'sessions#destroy', as: 'logout'
    post '/users/login', to: 'sessions#create'

    get '/users/profile', to: 'users#profile', as: 'profile'
    delete '/users/profile', to: 'users#destroy', as: 'destroy_user'
    get '/users/settings', to: 'users#settings', as: 'settings'
    patch '/users/settings/avatar', to: 'users#upload_avatar', as: 'upload_avatar'
    get '/users/:user_id', to: 'users#view_profile', as: 'view_profile'

    get '/auth/password', to: 'auth#edit_password', as: 'edit_password'
    patch '/auth/password', to: 'auth#update_password'

    get '/auth/reset', to: 'password_resets#new'
    post '/auth/reset', to: 'password_resets#create'

    get '/auth/reset/edit', to: 'password_resets#edit'
    patch '/auth/reset/edit', to: 'password_resets#update'

    patch '/users/change_name', to: 'users#change_username'

    get '/friends', to: 'friends#index'
    post '/friends', to: 'friends#send_invitation'
    patch '/friends/accept_invitation', to: 'friends#accept_invitation', as: 'accept_invitation'
    delete '/friends/delete_invitation', to: 'friends#delete_invitation', as: 'delete_invitation'
    delete '/friends/unfriend', to: 'friends#unfriend', as: 'unfriend'
  end
end

app/views/shared/_popup.html.erb
<%if flash[:notice] %>
  <p class="popup popup_notice">
    <i class="fa-solid fa-circle-info"></i>
    <%= flash[:notice] %>
  </p>
<%end %>
<%if flash[:alert] %>
  <p class="popup popup_alert">
    <i class="fa-solid fa-triangle-exclamation"></i>
    <%= flash[:alert] %>
  </p>
<%end %>

app/views/shared/_sidebar.html.erb
<nav class="sidebar">
  <div id="sidebar_logo">
    <%= link_to "/" do %>
      <%= image_tag "Bahnhofottos_ohneBackgr.png", alt: "Bahnhofottos Logo"%>
    <% end %>
  </div>

  <%= link_to root_path do %>
    <i class="fa-solid fa-message"></i>
  <% end %>
  <%= link_to map_path do %>
    <i class="fa-solid fa-map"></i>
  <% end %>
  <%= link_to friends_path do %>
    <i class="fa-solid fa-user-group"></i>
  <% end %>
  <%= link_to profile_path do %>
    <i class="fa-solid fa-user"></i>
  <% end %>

  <%= link_to settings_path do %>
    <i class="fa-solid fa-gear"></i>
  <% end %>
  <%= link_to info_path do %>
    <i class="fa-solid fa-circle-info"></i>
  <% end %>
</nav>