config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  get "/map", to: "map#index", as: :map
  patch "/map/station_image", to: "map#upload_station_image", as: "station_image"
  get "/map/station_image", to: "map#fetch_image"

  post "/api/overpass/stations", to: "overpass#stations"

  get "/proxy/map-tiles/thunderforest", to: "proxy#maptiles_thunderforest"
  get "/proxy/map-tiles/jawg", to: "proxy#maptiles_jawg"

  scope module: 'api' do
    get '/api/countries/:country_code', to: "country_data#fetch", as: "country_data"
  end

  get '/info', to: 'info#index', as: 'info'

  #Account system
  scope module: "account" do
    get '/users/sign_up', to: 'users#new', as: 'signup'
    post "/users/sign_up", to: 'users#create'

    get '/users/login', to: 'sessions#new', as: 'login'
    delete 'users/logout', to: 'sessions#destroy', as: 'logout'
    post '/users/login', to: 'sessions#create'

    get '/users/profile', to: 'users#profile', as: 'profile'
    delete '/users/profile', to: 'users#destroy', as: 'destroy_user'
    get '/users/settings', to: 'users#settings', as: 'settings'
    patch '/users/settings/avatar', to: 'users#upload_avatar', as: 'upload_avatar'
    get '/users/:user_id', to: 'users#view_profile', as: 'view_profile'

    get '/auth/password', to: 'auth#edit_password', as: 'edit_password'
    patch '/auth/password', to: 'auth#update_password'

    get '/auth/reset', to: 'password_resets#new'
    post '/auth/reset', to: 'password_resets#create'

    get '/auth/reset/edit', to: 'password_resets#edit'
    patch '/auth/reset/edit', to: 'password_resets#update'

    patch '/users/change_name', to: 'users#change_username'

    get '/friends', to: 'friends#index'
    post '/friends', to: 'friends#send_invitation'
    patch '/friends/accept_invitation', to: 'friends#accept_invitation', as: 'accept_invitation'
    delete '/friends/delete_invitation', to: 'friends#delete_invitation', as: 'delete_invitation'
    delete '/friends/unfriend', to: 'friends#unfriend', as: 'unfriend'
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  before_action :user_logged_in!, only: [:upload_station_image]
  layout 'map_layout'
  def index
    @page_libs = [:leaflet]
    json_file = Rails.root.join('public', 'data/grouped_countries.json')
    info_file = Rails.root.join('public', 'data/compiled_country_info.json')
    @country_data = JSON.parse(File.read(json_file))
    @country_info = JSON.parse(File.read(info_file))

    train_stations_json = []
    user_state = false
    if Current.user
      user_state = true
      @train_stations = Current.user.train_stations
      @train_stations.each do |train_station|
        image_url = url_for(train_station.image)

        train_station_json = {
          osm_id: train_station.osm_id,
          image_url: image_url
        }

        train_stations_json << train_station_json
      end
    end
    @photographed_stations = train_stations_json.to_json.html_safe

    show_station_id = params[:station]
    selected_country = params[:country]

    @session_info = {
      logged_in: user_state,
      show_station: show_station_id,
      show_country: selected_country
    }.to_json.html_safe
  end

  def upload_station_image

    existing_station = Current.user.train_stations.find_by(osm_id: train_station_params[:osm_id])
    if existing_station
      existing_station.image = train_station_params[:image]
      if existing_station.save
        redirect_to action: :index, country: view_params[:country], station: view_params[:osm_id]
      else
        redirect_to root_path, alert: "Error uploading"
      end
      return
    end

    @train_station = Current.user.train_stations.new(train_station_params)
    if @train_station.save
      redirect_to action: :index, country: view_params[:country], station: view_params[:osm_id]
    else
      redirect_to root_path, alert: "Error uploading"
    end
  end

  def fetch_image
    # Planning on dynamically sending the images to the frontend when popup is clicked
    id = params[:station_id]
    station = Current.user.train_stations.find_by(osm_id: id)

    if station
      send_data station.image.download, type: station.image.content_type, disposition: 'inline'
    end
  end

  private
  def train_station_params
    params.require(:user).permit(:osm_id, :image, :country, :name, :operator, :station_type)
  end

  def view_params
    params.require(:user).permit(:osm_id, :country)
  end
end

app/views/map/index.html.erb
<% content_for :head do %>
  <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css">
  <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css">
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
          integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
          crossorigin="">
  </script>
  <%= javascript_include_tag "/javascripts/leaflet-providers" %>

  <script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>
  <script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/fuse.js@6.6.2"></script>
  <%= javascript_include_tag "map_functions"%>

<% end %>

<script>
    let country_info = <%= @country_info.to_json.html_safe %>;
    let photographed_stations = {"stations" : <%= @photographed_stations %>};
    let session_info = <%= @session_info %>
</script>

<div class="map_container">
  <div id="map"></div>
</div>

<div class="dropdowns">
  <div class="station_search">
    <input type="text" name="search_query" id="station_search" placeholder="Search stations..." class="map_box_shadow">

    <ul class="matches map_box_shadow" id="matches">
    </ul>
  </div>

  <div class="dropdown">
    <select class="country_dropdown map_box_shadow" id="country_selection" name="selected_country" data-type="select-one" autocomplete="off" style="display: none">
      <% @country_data.each do |region, countries| %>
        <optgroup label="<%=region %>">
          <% countries.each do |country| %>
            <option value="<%= country['country_code'] %>" <%= 'selected=selected' if country['country_code'] == 'DE'%>><%= country['flag'] %> <%= country['name'] %></option>
          <% end %>
        </optgroup>
      <% end %>
    </select>
  </div>
</div>

<div id="hidden_form_wrapper">
  <%= form_with model: Current.user, id: "hidden_form", url: station_image_path, data: { turbo: false} do |f| %>
    <p>
      <%= f.file_field :image, accept: 'image/png, image/jpeg' , id: 'user_station_image'%>
    </p>
    <p>
      <%= f.text_field :osm_id, id: 'user_station_id'%>
    </p>
    <p>
      <%= f.text_field :country, id: 'user_station_country'%>
    </p>
    <p>
      <%= f.text_field :name, id: 'user_station_name'%>
    </p>
    <p>
      <%= f.text_field :operator, id: 'user_station_operator'%>
    </p>
    <p>
      <%= f.text_field :station_type, id: 'user_station_type'%>
    </p>

    <div class="actions">
      <%= f.submit "Upload picture" , id: "image_upload_submit"%>
    </div>
  <%end %>
</div>